### PR TITLE
Fix/smooth height estimation(autoware)

### PR DESCRIPTION
**Pull request by KYabuuchi**
I modified the smoothing_node to only enqueue subscribed positions when the vehicle is in motion.
This change ensures that the altitude estimation continues accurately even when the vehicle stops.

In the past, the smoothing_node pushed the data in queue every time and extract data with velocity when calculating the moving average. As a result, when the vehicle stoped, values couldn't be extracted from the queue, causing the altitude to become 0.

The following figure shows the estimated height being zero when the vehicle stops.
image

### Note
* `moving_ratio_threshold` is not used.

### CODE REVIEW

**Comment by rsasaki0109** [comment]
@Aoki-Takanose @OsamuSekino 
Just to confirm, I understand that the "moving_judgment_threshold" is a threshold used due to issues with Doppler velocity at low speeds. However, Doppler velocity is not used here. Do you know why "moving_judgment_threshold" is being used for filtering in this context?

**Review by rsasaki0109 — APPROVED** [review]

**Comment by rsasaki0109** [comment]
Thank you. The changes look fine, so I'll merge them.

**Comment by rsasaki0109** [comment]
@Aoki-Takanose 
Just to confirm, I understand that the moving_judgment_threshold is a threshold used because there are issues with the Doppler velocity at low speeds. However, the Doppler velocity is not used here. Do you know why we are filtering with the moving_judgment_threshold here?

**Comment by Aoki-TK** [comment]
This is because Eagleye requires that GNSS fusion, not just GNSS Doppler, be above a certain speed.
This is Eagleye's concept, and the same process is applied to other estimation parts as well.

If there are any problems with this part of the estimation, they can be solved by modifying the parameter values.

**Pull request merged**
